connector.class=org.apache.iceberg.connect.IcebergSinkConnector
tasks.max=2
topics=yt-sales-iac-records

# Bronze table is explicitly bootstrapped from infra/sql/iceberg.
iceberg.tables=iata_sales_iac_bronze.sales_raw
iceberg.tables.auto-create-enabled=false
iceberg.tables.evolve-schema-enabled=false
iceberg.tables.schema-case-insensitive=false

iceberg.catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
iceberg.catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO
iceberg.catalog.client.region=ap-southeast-1
iceberg.catalog.warehouse=s3://yt-sales-iac-lakehouse-<ACCOUNT_ID>/bronze

iceberg.control.topic=yt-sales-iac-control-iceberg
iceberg.control.commit.interval-ms=10000

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

errors.tolerance=all
errors.deadletterqueue.topic.name=yt-sales-iac-errors
errors.deadletterqueue.context.headers.enable=true
errors.deadletterqueue.topic.replication.factor=2
